# Generated by Django 5.1.4 on 2024-12-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
