# Generated by Django 5.1.4 on 2024-12-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0003_alter_audiofile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'verbose_name': 'Audio File', 'verbose_name_plural': 'Audio Files'},
        ),
        migrations.AddField(
            model_name='audiofile',
            name='made_from',
            field=models.ForeignKey(blank=True, help_text='Audio file used to create this one', null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioapp.audiofile'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(help_text='Upload an audio file', upload_to=''),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='processed',
            field=models.BooleanField(default=False, help_text='Is the file processed?'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='style',
            field=models.CharField(help_text='Style of the audio file', max_length=50),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='title',
            field=models.CharField(help_text='Title of the audio file', max_length=100),
        ),
    ]
