# Generated by Django 5.1.4 on 2024-12-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0004_alter_audiofile_options_audiofile_made_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioapp.audiofile')),
            ],
            options={
                'verbose_name': 'Play History',
                'verbose_name_plural': 'Play Histories',
            },
        ),
    ]
